### ISSUE TITLE
FRP: Way to access internal

### ISSUE THREAD

**Issue by Major-Eth** [yearn/yearn-vaults-descriptions#11]
### What is your proposal 🚀
There is currently no way to access the internal page.
Vercel has a nice way to access the branding system by right clicking the logo : not invasive, hidden in plain sight and accessible from any page. This could be a nice solution.

### What does this solve ? 🛠
This would provide an easy access to the internal part

### More 🔎
*N/A*

**Comment by DarkGhost7** [comment]
This would be a nice feature
