### ISSUE TITLE
Bug: Tokens with additional override paramaters showing up

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/yearn-vaults-descriptions#39]
### What happened 🆘
https://github.com/yearn/yearn-meta/blob/master/data/tokens/1/0xC4C319E2D4d66CcA4464C0c2B32c9Bd23ebe784e.json#L6
This token is showing up as a token that isn't in the repo when I can see it is in fact already added to the repo. Maybe this is either a cache issue or its due to the override parameters on this specific token.

### To Reproduce 🔂
![image](https://user-images.githubusercontent.com/38810205/158283553-a07b5958-f37e-4f96-b33b-09427e435d00.png)

### More 🔎
- Browser : Vivaldi

**Comment by DarkGhost7** [comment]
![image](https://user-images.githubusercontent.com/38810205/158284006-5b2dcb60-8db3-4962-88d1-cee752607fc7.png)
This is the case for all three shown here

**Comment by 0xYao** [comment]
> This token is showing up as a token that isn't in the repo when I can see it is in fact already added to the repo.

Maybe the wording below is better? It took me a while to figure out what you meant 😄 .

"This token shows up as a missing token [here](https://vaults.yearn.finance/internal/missing-tokens), but I can see it is in fact already added to the [repo](https://github.com/yearn/yearn-meta/blob/master/data/tokens/1/0xC4C319E2D4d66CcA4464C0c2B32c9Bd23ebe784e.json#L6)."

**Comment by 0xYao** [comment]
> ![image](https://user-images.githubusercontent.com/38810205/158284006-5b2dcb60-8db3-4962-88d1-cee752607fc7.png) This is the case for all three shown here

The token addresses are added to the `yearn-meta` repo, but the vault addresses aren't. 

e.g. the vault address for Curve MIM-UST is `0xd8C620991b8E626C099eAaB29B1E3eEa279763bb`, but the vault metada file `yearn-meta/data/vaults/0xd8C620991b8E626C099eAaB29B1E3eEa279763bb.json` is not found  in the `yearn-meta` repo

**Comment by 0xYao** [comment]
Happy to raise the PR in the `yearn-meta` repo if you agree adding vault metadata files fixes the issue.

**Comment by DarkGhost7** [comment]
> > This token is showing up as a token that isn't in the repo when I can see it is in fact already added to the repo.
> 
> Maybe the wording below is better? It took me a while to figure out what you meant 😄 .
> 
> "This token shows up as a missing token on the [yearn Vaults site](https://vaults.yearn.finance/internal/missing-tokens), but I can see it is in fact already added to the [repo](https://github.com/yearn/yearn-meta/blob/master/data/tokens/1/0xC4C319E2D4d66CcA4464C0c2B32c9Bd23ebe784e.json#L6)."

Sorry yes that is correct my fault

**Comment by DarkGhost7** [comment]
> > ![image](https://user-images.githubusercontent.com/38810205/158284006-5b2dcb60-8db3-4962-88d1-cee752607fc7.png) This is the case for all three shown here
> 
> The token addresses are added to the `yearn-meta` repo, but the vault addresses aren't. 
> 
> e.g. the vault address for Curve MIM-UST is `0xd8C620991b8E626C099eAaB29B1E3eEa279763bb`, but the vault metada file `yearn-meta/data/vaults/0xd8C620991b8E626C099eAaB29B1E3eEa279763bb.json` is not found  in the `yearn-meta` repo

Ah I see sorry
