### ISSUE TITLE
FRP: Page to view missing translations for the protocols

### ISSUE THREAD

**Issue by Major-Eth** [yearn/yearn-vaults-descriptions#45]
### What is your proposal 🚀
- The Protocols can be found here: https://meta.yearn.network/protocols
- Each Protocol should have one name, one description and an object of localization with various language with name and description for each of them.
- Add a new tab in the internal folder to detect protocols with no translations or missing translations
- A missing translation can be detected when `protocol.description === protocol.localization[locale].description` (for example).
- A dropdown/filter should be available to check by locale

### What does this solve ? 🛠
Will ease the work to find missing strategies translations

### More 🔎
*N/A*

**Comment by 0xYao** [comment]
I am picking this one up 😃

**Comment by 0xYao** [comment]
> ### What is your proposal 🚀
> * The Protocols can be found here: https://meta.yearn.network/protocols
> * Each Protocol should have one name, one description and an object of localization with various language with name and description for each of them.
> * Add a new tab in the internal folder to detect protocols with no translations or missing translations
> * A missing translation can be detected when `protocol.description === protocol.localization[locale].description` (for example).
> * A dropdown/filter should be available to check by locale
> 
> ### What does this solve ? 🛠
> Will ease the work to find missing strategies translations
> 
> ### More 🔎

Hey, I have implemented the feature in #47 😄
