### ISSUE TITLE
Bug: I suggest to use 中文 instead of 中国人.

### ISSUE THREAD

**Issue by xiaona423** [yearn/yearn-vaults-descriptions#50]
### What happened 🆘
**website: https://vaults.yearn.finance/,  language on the left corner, 中国人 is a bit weird.**

### To Reproduce 🔂
Steps to reproduce the behavior: I suggest to use 中文 instead of 中国人.

### More 🔎
- Browser : https://vaults.yearn.finance/

**Comment by DarkGhost7** [comment]
https://vaults.yearn.finance/internal/missing-translations also listed here
