### ISSUE TITLE
FRP: Migrate to Typescript

### ISSUE THREAD

**Issue by Majorfi** [yearn/yearn-vaults-descriptions#59]
### What is your proposal 🚀
Move the repo to typescript, based on the web-template: https://github.com/yearn/web-template
Same eslint, tsconfig etc. should be used. Yearn Web Lib should be integrated with it, just like in the `_app.tsx` file in web-template repo.

### What does this solve ? 🛠
Better consistency for Yearn Org

### More 🔎
*N/A*

**Comment by 0xMirim** [comment]
I haven't migrated a React repo to Typescript before but it should be straightforward. I currently have a local branch which I've setup to use Typescript (specifically tsconfig etc. from yearn/web-template). The plan is to make required config changes and update the site file by file converting js files to tsx.

**Comment by 0xMirim** [comment]
@Majorfi I recently finished migrating the repo and welcome feedback on the pull request.
